# Generated by Django 4.0.4 on 2022-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('word', models.TextField()),
            ],
        ),
    ]
