# Generated by Django 4.0.4 on 2022-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField()),
            ],
        ),
    ]
