# Generated by Django 4.0.4 on 2022-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.BigIntegerField()),
                ('full_name', models.TextField()),
                ('sana', models.DateTimeField(auto_now=True)),
                ('kanal', models.TextField()),
                ('xabar', models.TextField()),
                ('soz', models.TextField()),
            ],
        ),
    ]
